import { UniversalComponent, ComponentFilePayload, EcosystemFlavor } from '../schema';
import { generateOuterLayerFiles } from '../templates/outer-layer';
import { CORE_COMPONENT_DEPENDENCIES } from '../templates/common-deps';

export const cursorTooltipComponent: UniversalComponent = {
	id: 'cursor-tooltip',
	name: 'Cursor Tooltip',
	slug: 'cursor-tooltip',
	category: 'primitives',
	description: 'Tactile cursor-following tooltip with continuous exponential lerp tracking, boundary viewport collision clamping, multi-variant tokens, and zero Framer Motion dependencies.',
	version: '1.0.0',
	props: [
		{
			name: 'content',
			label: 'Tooltip Content',
			type: 'string',
			defaultValue: 'Explore Showcase',
			description: 'Text or badge label displayed inside the trailing tooltip.',
		},
		{
			name: 'springDamping',
			label: 'Spring Damping',
			type: 'number',
			defaultValue: 20,
			min: 6,
			max: 40,
			step: 2,
			description: 'Exponential smoothing factor for trailing cursor physics (higher = snappy, lower = trailing glide).',
		},
		{
			name: 'offsetX',
			label: 'Offset X (px)',
			type: 'number',
			defaultValue: 16,
			min: 0,
			max: 48,
			step: 2,
			description: 'Horizontal distance from cursor to tooltip origin in pixels.',
		},
		{
			name: 'offsetY',
			label: 'Offset Y (px)',
			type: 'number',
			defaultValue: 16,
			min: 0,
			max: 48,
			step: 2,
			description: 'Vertical distance from cursor to tooltip origin in pixels.',
		},
		{
			name: 'variant',
			label: 'Badge Variant',
			type: 'select',
			defaultValue: 'frosted',
			options: [
				{ label: 'macOS Frosted Glass', value: 'frosted' },
				{ label: 'High-Contrast Accent', value: 'accent' },
				{ label: 'Dark Charcoal', value: 'dark' },
				{ label: 'Minimal Border', value: 'minimal' },
				{ label: 'Emerald Glow', value: 'glow' },
			],
			description: 'Visual token styling of the floating tooltip badge.',
		},
		{
			name: 'direction',
			label: 'Direction',
			type: 'select',
			defaultValue: 'bottom-right',
			options: [
				{ label: 'Bottom Right', value: 'bottom-right' },
				{ label: 'Bottom Left', value: 'bottom-left' },
				{ label: 'Top Right', value: 'top-right' },
				{ label: 'Top Left', value: 'top-left' },
				{ label: 'Top', value: 'top' },
				{ label: 'Bottom', value: 'bottom' },
				{ label: 'Left', value: 'left' },
				{ label: 'Right', value: 'right' },
			],
			description: 'Directional orientation and quadrant placement relative to cursor pointer.',
		},
		{
			name: 'collisionPadding',
			label: 'Collision Padding (px)',
			type: 'number',
			defaultValue: 12,
			min: 4,
			max: 32,
			step: 2,
			description: 'Safe margin in pixels between tooltip and viewport edges to prevent clipping.',
		},
	],
	defaultProps: {
		content: 'Explore Showcase',
		springDamping: 20,
		direction: 'bottom-right',
		offsetX: 16,
		offsetY: 16,
		variant: 'frosted',
		collisionPadding: 12,
	},
	dependencies: CORE_COMPONENT_DEPENDENCIES,
	generateCode: (flavor: EcosystemFlavor, props: Record<string, unknown>, options?: { eject?: boolean }): ComponentFilePayload[] => {
		return generateOuterLayerFiles(
			{
				id: 'cursor-tooltip',
				name: 'Cursor Tooltip',
				slug: 'cursor-tooltip',
				category: 'primitives',
				pascalName: 'CursorTooltip',
				snakeName: 'cursor_tooltip',
				description: 'Tactile cursor-following tooltip with continuous exponential lerp tracking and viewport boundary collision clamping.',
				defaultTailwindClass: 'relative inline-block cursor-pointer',
			},
			flavor,
			props,
			options
		);
	},
};
