import { UniversalComponent, ComponentFilePayload, EcosystemFlavor } from '../schema';
import { generateOuterLayerFiles } from '../templates/outer-layer';
import { CORE_COMPONENT_DEPENDENCIES } from '../templates/common-deps';

export const floatingDockComponent: UniversalComponent = {
	id: 'floating-dock',
	name: 'Floating Dock',
	slug: 'floating-dock',
	category: 'navigation',
	description: 'High-performance kinetic floating application dock with continuous C1-cosine proximity distribution, multi-directional orientation, and zero layout thrashing.',
	version: '1.0.0',
	props: [
		{
			name: 'direction',
			label: 'Dock Direction / Orientation',
			type: 'select',
			defaultValue: 'bottom',
			options: [
				{ label: 'Bottom (Default)', value: 'bottom' },
				{ label: 'Top Bar', value: 'top' },
				{ label: 'Left Rail', value: 'left' },
				{ label: 'Right Rail', value: 'right' },
			],
			description: 'Orientation and shelf alignment edge of the dock and tooltip positions.',
		},
		{
			name: 'baseSize',
			label: 'Base Item Size (px)',
			type: 'number',
			defaultValue: 36,
			min: 32,
			max: 64,
			step: 2,
			description: 'Default width and height of dock items at rest.',
		},
		{
			name: 'maxMagnification',
			label: 'Max Boost Factor',
			type: 'number',
			defaultValue: 0.75,
			min: 0.1,
			max: 1.2,
			step: 0.05,
			description: 'Maximum scale multiplier at zero distance.',
		},
		{
			name: 'influenceRadius',
			label: 'Influence Radius (px)',
			type: 'number',
			defaultValue: 60,
			min: 40,
			max: 160,
			step: 5,
			description: 'Influence spread of the Gaussian proximity curve.',
		},
		{
			name: 'showLabels',
			label: 'Show App Labels',
			type: 'boolean',
			defaultValue: true,
			description: 'Display macOS-style frosted tooltips on icon hover/focus.',
		},
		{
			name: 'panelStyle',
			label: 'Dock Panel Style',
			type: 'select',
			defaultValue: 'translucent',
			options: [
				{ label: 'macOS Frosted Glass', value: 'glass' },
				{ label: 'Dark Translucent', value: 'translucent' },
				{ label: 'Frameless Minimal', value: 'minimal' },
			],
			description: 'Visual backing shelf styling of the dock.',
		},
	],
	defaultProps: {
		direction: 'bottom',
		baseSize: 36,
		maxMagnification: 0.75,
		influenceRadius: 60,
		showLabels: true,
		panelStyle: 'translucent',
	},
	dependencies: {
		react: ['@exhuma/core', 'clsx', '@tabler/icons-react'],
		nextjs: ['@exhuma/core', 'clsx', '@tabler/icons-react'],
		vue: ['clsx'],
		svelte: ['clsx'],
		solid: ['clsx'],
		angular: [],
		astro: [],
		blade: [],
		vanilla: [],
		wordpress: [],
		webcomponent: [],
		'react-native': [],
		flutter: [],
	},
	generateCode: (flavor: EcosystemFlavor, props: Record<string, unknown>, options?: { eject?: boolean }): ComponentFilePayload[] => {
		return generateOuterLayerFiles(
			{
				id: 'floating-dock',
				name: 'Floating Dock',
				slug: 'floating-dock',
				category: 'navigation',
				pascalName: 'FloatingDock',
				snakeName: 'floating_dock',
				description: 'High-performance kinetic floating application dock with continuous C1-cosine proximity distribution.',
				defaultTailwindClass: 'relative inline-flex items-end gap-2.5 rounded-2xl border border-border/80 bg-background/80 dark:bg-card/80 p-2.5 shadow-2xl backdrop-blur-xl',
				compoundParts: [
					{ name: 'Root', primitiveExport: 'FloatingDock', defaultClass: 'relative inline-flex items-end gap-2.5 rounded-2xl border border-border/80 bg-background/80 dark:bg-card/80 p-2.5 shadow-2xl backdrop-blur-xl' },
					{ name: 'Item', primitiveExport: 'DockItem', defaultClass: 'relative flex shrink-0 items-center justify-center rounded-xl border border-border/70 bg-card/80 shadow-md backdrop-blur-md' },
					{ name: 'Icon', primitiveExport: 'DockIcon', defaultClass: 'flex size-full items-center justify-center' },
					{ name: 'Label', primitiveExport: 'DockLabel', defaultClass: 'text-xs font-semibold' },
				],
			},
			flavor,
			props,
			options
		);
	},
};
